In [2]:
import numpy as np
import pandas as pd

In [ ]:
# NumPy vs List

# Numpy is fast while list is slow

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
a.shape

(3,)

In [6]:
b = np.array([[1,2,3], [2,3,4.0]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 3)

In [14]:
c = np.array([4.0, 2.3, 1.2], dtype = 'int32')

In [15]:
c.dtype

dtype('int32')

In [16]:
c.itemsize

4

In [17]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [21]:
# Accessing specific element a[r, c]

a[1,5]

13

In [25]:
# Get a specific row

a[0, 0:-1]

array([1, 2, 3, 4, 5, 6])

In [27]:
a[0, 1:-1:2]

array([2, 4, 6])

In [28]:
# Replacing an existing element

a[1, 3] = 99

In [29]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 99, 12, 13, 14]])

In [43]:
# 3-dimensional Eg

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]],[[9,10], [10,11]]])

In [44]:
d3.ndim

3

In [45]:
d3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [10, 11]]])

In [49]:
# Get specific element

d3[2,0,0]

9

In [54]:
d3[0, :, :]

array([[1, 2],
       [3, 4]])

In [59]:
# array with zeros

np.zeros((1,7,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [61]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
np.full((2,3),455)

array([[455, 455, 455],
       [455, 455, 455]])

In [66]:
np.random.rand(4,1)

array([[0.71992165],
       [0.42478311],
       [0.8567101 ],
       [0.58019326]])

In [67]:
np.random.random_sample(a.shape)

array([[0.76725061, 0.76409792, 0.960403  , 0.03398052, 0.08202614,
        0.74914892, 0.4263151 ],
       [0.99775094, 0.28245071, 0.95021509, 0.63563824, 0.81867029,
        0.12937612, 0.51876234]])

In [86]:
np.random.randint(-10,10, size=(1,2))

array([[  6, -10]])

In [89]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
x=np.array((1,2,3,4,5))
y=x.copy()
y[1] = 5
x

array([1, 2, 3, 4, 5])

In [101]:
np.sin(x)
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
   0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.03982088  0.84385396  0.90744678
   0.13673722]]


In [103]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [114]:
y = np.random.randint(10, size=(3,2))
y

array([[7, 9],
       [5, 8],
       [8, 3]])

In [116]:
np.matmul(x, y)

array([[20., 20.],
       [20., 20.]])

In [117]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [120]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [121]:
arr = np.array([[1,2,3], [24,56,78]])

In [122]:
arr.ndim

2

In [124]:
for i in arr:
    for j in i:
        print(j)

1
2
3
24
56
78


In [125]:
# nditer function

for i in np.nditer(arr):
    print(i)

1
2
3
24
56
78


In [127]:
arr1 = np.array([[23,45,67], [12,34,56]])
arr2 = np.array([[43,5,7], [1,4,6]])

In [130]:
arr = np.concatenate((arr1, arr2), axis=1)

In [131]:
arr

array([[23, 45, 67, 43,  5,  7],
       [12, 34, 56,  1,  4,  6]])

## Series

In [19]:
ice_cream = ['chocolate', 'vanilla', 'strawberry', 'rum raisin', 'chocolate']

ice_cream = pd.Series(ice_cream)

In [5]:
sushi = {
        "Salmon": "Orange",
        "Tuna": "Red",
        "Eel": "Brown"
}

pd.Series(sushi)

Salmon    Orange
Tuna         Red
Eel        Brown
dtype: object

In [6]:
prices = pd.Series([2.99, 4.56, 8.32])

In [13]:
prices.append(pd.Series([2.5])), prices.

0    2.99
1    4.56
2    8.32
0    2.50
dtype: float64

In [16]:
ice_cream.size

4

In [20]:
ice_cream.is_unique

False

In [22]:
ice_cream.values

array(['chocolate', 'vanilla', 'strawberry', 'rum raisin', 'chocolate'],
      dtype=object)

In [26]:
type(ice_cream)

pandas.core.series.Series

In [25]:
ice_cream.index

RangeIndex(start=0, stop=5, step=1)

In [31]:
fruits = ['Apple', 'Orange', 'Pineapple', 'Grape', 'Blueberry', 'Plum', 'Pomegranate']
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Monday']

In [32]:
pd.Series(fruits, index = weekdays)

Monday             Apple
Tuesday           Orange
Wednesday      Pineapple
Thursday           Grape
Friday         Blueberry
Saturday            Plum
Monday       Pomegranate
dtype: object

In [35]:
foods = ["French Fries", "Chicken Nuggets", "Celery", "Carrots"]
dipping_sauces = ["BBQ", "Honey Mustard", "Ranch", "Sriracha"]

pd.Series(foods, dipping_sauces)

pd.Series(data=dipping_sauces, index=foods)

French Fries                 BBQ
Chicken Nuggets    Honey Mustard
Celery                     Ranch
Carrots                 Sriracha
dtype: object

In [40]:
pokemon = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\pokemon.csv', usecols=['Name'], squeeze=True)

In [46]:
len(pokemon)

800

In [49]:
type(pokemon)
dir(pokemon)
sorted(pokemon)

['Abomasnow',
 'AbomasnowMega Abomasnow',
 'Abra',
 'Absol',
 'AbsolMega Absol',
 'Accelgor',
 'AegislashBlade Forme',
 'AegislashShield Forme',
 'Aerodactyl',
 'AerodactylMega Aerodactyl',
 'Aggron',
 'AggronMega Aggron',
 'Aipom',
 'Alakazam',
 'AlakazamMega Alakazam',
 'Alomomola',
 'Altaria',
 'AltariaMega Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'AmpharosMega Ampharos',
 'Anorith',
 'Arbok',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Ariados',
 'Armaldo',
 'Aromatisse',
 'Aron',
 'Articuno',
 'Audino',
 'AudinoMega Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'BanetteMega Banette',
 'Barbaracle',
 'Barboach',
 'Basculin',
 'Bastiodon',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'BeedrillMega Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blastoise',
 'BlastoiseMega Blastoise',
 'Blaziken',
 'BlazikenMe

In [56]:
pokemon.sort_values(axis=0, ascending=True, kind='quicksort').head()

510                  Abomasnow
511    AbomasnowMega Abomasnow
68                        Abra
392                      Absol
393            AbsolMega Absol
Name: Name, dtype: object

In [57]:
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [60]:
flavors = ["Spicy Sweet Chili", "Cool Ranch", "Nacho Cheese", "Salsa Verde"]

doritos = pd.Series(flavors)

In [62]:
doritos.sort_values(ascending=False)

0    Spicy Sweet Chili
3          Salsa Verde
2         Nacho Cheese
1           Cool Ranch
dtype: object

In [101]:
pokemon = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\pokemon.csv', usecols=['Name', 'Type 1'], index_col='Name').squeeze()

In [102]:
pokemon.sort_index(ascending=True).head()

Name
Abomasnow                    Grass
AbomasnowMega Abomasnow      Grass
Abra                       Psychic
Absol                         Dark
AbsolMega Absol               Dark
Name: Type 1, dtype: object

In [103]:
pokemon["Absol"]

'Dark'

In [72]:
flavors = ["Red", "Blue", "Green", "Orange"]
gatorade = pd.Series(flavors).sort_values()


In [74]:
gatorade.sort_index()

0       Red
1      Blue
2     Green
3    Orange
dtype: object

In [81]:
'Abra' in pokemon

True

In [84]:
pokemon = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\pokemon.csv', usecols=['Name']).squeeze()

In [85]:
pokemon

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [94]:
pokemon[[1, 5]]

1       Ivysaur
5    Charmeleon
Name: Name, dtype: object

In [100]:
pokemon[-6:-1]

794       Zygarde50% Forme
795                Diancie
796    DiancieMega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
Name: Name, dtype: object

In [105]:
guitars_dict = {
    "Fender Telecaster": "Baby Blue",
    "Gibson Les Paul": "Sunburst",
    "ESP Eclipse": "Dark Green"}

In [106]:
pd.Series(guitars_dict)

Fender Telecaster     Baby Blue
Gibson Les Paul        Sunburst
ESP Eclipse          Dark Green
dtype: object

In [108]:
pokemon.head()

Name
Bulbasaur                Grass
Ivysaur                  Grass
Venusaur                 Grass
VenusaurMega Venusaur    Grass
Charmander                Fire
Name: Type 1, dtype: object

In [113]:
print(pokemon.get('Bulba'))

None


In [116]:
pokemon.get('Charmander', 'None')

'Fire'

## Overwrite a series value

In [117]:
pokemon = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\pokemon.csv', usecols=['Name']).squeeze()

In [118]:
pokemon.head()

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [122]:
pokemon[0] = 'Borisor'
pokemon[1500] = 'nothing'

In [131]:
pokemon[[1, 2, 4]] = ["Ivy", 'Firman', 'Blazemon']

In [132]:
pokemon.head()

0                  Borisor
1                      Ivy
2                   Firman
3    VenusaurMega Venusaur
4                 Blazemon
Name: Name, dtype: object

In [140]:
pokemon = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\pokemon.csv', usecols=['Name', 'Type 1'], index_col='Name').squeeze()

In [143]:
pm = pokemon.copy()

In [144]:
pm

Name
Bulbasaur                  Grass
Ivysaur                    Grass
Venusaur                   Grass
VenusaurMega Venusaur      Grass
Charmander                  Fire
                          ...   
Diancie                     Rock
DiancieMega Diancie         Rock
HoopaHoopa Confined      Psychic
HoopaHoopa Unbound       Psychic
Volcanion                   Fire
Name: Type 1, Length: 800, dtype: object

In [150]:
google_stockprice = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\google_stock_price.csv').squeeze()

In [154]:
google_stockprice.count()
google_stockprice.sum()
google_stockprice.mean()
google_stockprice.std()

173.18720477113106

## Broadcasting

In [156]:
google_stockprice * 3
google_stockprice + 19

0        69.12
1        73.10
2        73.65
3        71.38
4        71.95
         ...  
3007    791.88
3008    790.07
3009    792.18
3010    790.61
3011    801.22
Name: Stock Price, Length: 3012, dtype: float64

In [169]:
pokemon.value_counts()
pokemon.value_counts(ascending=True).head()
pokemon.value_counts(sort=False)
pokemon.value_counts(normalize=True) * 100

Water       14.000
Normal      12.250
Grass        8.750
Bug          8.625
Psychic      7.125
Fire         6.500
Rock         5.500
Electric     5.500
Ground       4.000
Dragon       4.000
Ghost        4.000
Dark         3.875
Poison       3.500
Fighting     3.375
Steel        3.375
Ice          3.000
Fairy        2.125
Flying       0.500
Name: Type 1, dtype: float64

In [173]:
pokemon

Name
Bulbasaur                  Grass
Ivysaur                    Grass
Venusaur                   Grass
VenusaurMega Venusaur      Grass
Charmander                  Fire
                          ...   
Diancie                     Rock
DiancieMega Diancie         Rock
HoopaHoopa Confined      Psychic
HoopaHoopa Unbound       Psychic
Volcanion                   Fire
Name: Type 1, Length: 800, dtype: object

In [175]:
mappings = {
        "Grass": "Classic",
        "Fire": "Dynamic"
}

In [176]:
pokemon.map(mappings)

Name
Bulbasaur                Classic
Ivysaur                  Classic
Venusaur                 Classic
VenusaurMega Venusaur    Classic
Charmander               Dynamic
                          ...   
Diancie                      NaN
DiancieMega Diancie          NaN
HoopaHoopa Confined          NaN
HoopaHoopa Unbound           NaN
Volcanion                Dynamic
Name: Type 1, Length: 800, dtype: object

## DataFrame

In [1]:
import pandas as pd

In [2]:
nba = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\nba.csv')

In [5]:
nba.head(5)

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [6]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [11]:
revenue = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\revenue.csv', index_col=['Date'])

In [13]:
revenue['New York'].sum()

5475

In [18]:
revenue.Miami

Date
1/1/16     499
1/2/16     534
1/3/16     933
1/4/16     885
1/5/16     253
1/6/16     497
1/7/16     115
1/8/16     886
1/9/16     823
1/10/16    216
Name: Miami, dtype: int64

In [22]:
revenue[['Miami', 'New York', 'Los Angeles']]

Miami  New York  Los Angeles
Date                                 
1/1/16     499       985          122
1/2/16     534       738          788
1/3/16     933        14           20
1/4/16     885       730          904
1/5/16     253       114           71
1/6/16     497       936          502
1/7/16     115       123          996
1/8/16     886       935          492
1/9/16     823       846          954
1/10/16    216        54          285

In [40]:
nba = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\nba.csv')
nba.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [29]:
nba['Increment'] = '10' + '%'

In [30]:
nba.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary Increment  
0              Texas  7730337.0       10%  
1          Marquette  6796117.0       10%  
2  Boston University        NaN       10%  
3      Georgia State  1148640.0       10%  
4                NaN  5000000.0       10%

In [32]:
nba.insert(loc = 3, column = 'Sport', value = 'Basketball')

In [33]:
nba.head(3)

Name            Team  Number       Sport Position   Age Height  \
0  Avery Bradley  Boston Celtics     0.0  Basketball       PG  25.0    6-2   
1    Jae Crowder  Boston Celtics    99.0  Basketball       SF  25.0    6-6   
2   John Holland  Boston Celtics    30.0  Basketball       SG  27.0    6-5   

   Weight            College     Salary  
0   180.0              Texas  7730337.0  
1   235.0          Marquette  6796117.0  
2   205.0  Boston University        NaN

In [34]:
nba.insert(loc = 7, column='Leage', value='National Basketball Association')

In [39]:
nba.head()

Name            Team  Number       Sport Position   Age Height  \
0  Avery Bradley  Boston Celtics     0.0  Basketball       PG  25.0    6-2   
1    Jae Crowder  Boston Celtics    99.0  Basketball       SF  25.0    6-6   
2   John Holland  Boston Celtics    30.0  Basketball       SG  27.0    6-5   
3    R.J. Hunter  Boston Celtics    28.0  Basketball       SG  22.0    6-5   
4  Jonas Jerebko  Boston Celtics     8.0  Basketball       PF  29.0   6-10   

                             Leage  Weight            College     Salary  
0  National Basketball Association   180.0              Texas  7730337.0  
1  National Basketball Association   235.0          Marquette  6796117.0  
2  National Basketball Association   205.0  Boston University        NaN  
3  National Basketball Association   185.0      Georgia State  1148640.0  
4  National Basketball Association   231.0                NaN  5000000.0

In [48]:
nba.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [42]:
nba['Age'].add(29)

0      54.0
1      54.0
2      56.0
3      51.0
4      58.0
       ... 
453    55.0
454    53.0
455    55.0
456    55.0
457     NaN
Name: Age, Length: 458, dtype: float64

In [53]:
nba['Position'].value_counts(normalize = True)*100
nba['Salary'].value_counts()

947276.0     31
845059.0     18
525093.0     13
981348.0      6
1100602.0     5
             ..
1242720.0     1
2489530.0     1
5103120.0     1
9463484.0     1
700902.0      1
Name: Salary, Length: 309, dtype: int64

## Drop Null/ Missing Value

In [59]:
nba = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\nba.csv')
nba

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [60]:
nba.dropna(how = 'all')

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  

[457 rows x 9 columns]

In [64]:
nba.dropna(subset=['College'])

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
..             ...             ...     ...      ...   ...    ...     ...   
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
6                  LSU  1170960.0  
..                 ...        ...  
449               Duke  1348440.0  
451             Dayton   981348.0  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
456             Kansas   947276.0  

[373 rows x 9 columns]

In [69]:
nba = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\nba.csv')
nba.tail()

Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler   
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN   
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN   
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas   
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN   

        Salary  
453  2433333.0  
454   900000.0  
455  2900000.0  
456   947276.0  
457        NaN

In [70]:
nba['College'].fillna('Unknown')

0                  Texas
1              Marquette
2      Boston University
3          Georgia State
4                Unknown
             ...        
453               Butler
454              Unknown
455              Unknown
456               Kansas
457              Unknown
Name: College, Length: 458, dtype: object

In [73]:
nba['Salary'].fillna('1000000000')

0      7.73034e+06
1      6.79612e+06
2       1000000000
3      1.14864e+06
4            5e+06
          ...     
453    2.43333e+06
454         900000
455        2.9e+06
456         947276
457     1000000000
Name: Salary, Length: 458, dtype: object

In [4]:
nba = pd.read_csv(r'D:\Learning & Projects\Python\Pandas\Boris\nba.csv').dropna(how='all')

In [5]:
nba['Age'].isnull().sum()
nba['Age'].astype('int')
#nba["Age"].astype(int)

0      25
1      25
2      27
3      22
4      29
       ..
452    20
453    26
454    24
455    26
456    26
Name: Age, Length: 457, dtype: int32

In [86]:
nba['Salary'].astype(int) # cannot convert to desired datatype inless we solve the na values

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [8]:
nba['Position'] = nba['Position'].astype('category')

In [9]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Name      457 non-null    object  
 1   Team      457 non-null    object  
 2   Number    457 non-null    float64 
 3   Position  457 non-null    category
 4   Age       457 non-null    float64 
 5   Height    457 non-null    object  
 6   Weight    457 non-null    float64 
 7   College   373 non-null    object  
 8   Salary    446 non-null    float64 
dtypes: category(1), float64(4), object(4)
memory usage: 32.8+ KB


In [17]:
nba.sort_values(by='Salary', ascending=False)
nba.sort_values(by='Salary', na_position='last')

Name                    Team  Number Position   Age  \
32   Thanasis Antetokounmpo         New York Knicks    43.0       SF  23.0   
291         Orlando Johnson    New Orleans Pelicans     0.0       SG  27.0   
130            Phil Pressey            Phoenix Suns    25.0       PG  25.0   
135           Alan Williams            Phoenix Suns    15.0        C  23.0   
175            Jordan McRae     Cleveland Cavaliers    12.0       SG  25.0   
..                      ...                     ...     ...      ...   ...   
273          Alex Stepheson       Memphis Grizzlies    35.0       PF  28.0   
350           Briante Weber              Miami Heat    12.0       PG  23.0   
353           Dorell Wright              Miami Heat    11.0       SF  30.0   
397            Axel Toupane          Denver Nuggets     6.0       SG  23.0   
409              Greg Smith  Minnesota Timberwolves     4.0       PF  25.0   

    Height  Weight                College    Salary  
32     6-7   205.0                    NaN   30888.0  
291    6-5   220.0       UC Santa Barbara   55722.0  
130   5-11   175.0               Missouri   55722.0  
135    6-8   260.0       UC Santa Barbara   83397.0  
175    6-5   179.0              Tennessee  111196.0  
..     ...     ...                    ...       ...  
273   6-10   270.0                    USC       NaN  
350    6-2   165.0  Virginia Commonwealth       NaN  
353    6-9   205.0                    NaN       NaN  
397    6-7   210.0                    NaN       NaN  
409   6-10   250.0           Fresno State       NaN  

[457 rows x 9 columns]

In [21]:
nba = nba.sort_values(by=['Team', 'Name'], ascending = [True, False])
nba

Name                Team  Number Position   Age Height  \
322    Walter Tavares       Atlanta Hawks    22.0        C  24.0    7-3   
310  Tim Hardaway Jr.       Atlanta Hawks    10.0       SG  24.0    6-6   
321    Tiago Splitter       Atlanta Hawks    11.0        C  31.0   6-11   
320   Thabo Sefolosha       Atlanta Hawks    25.0       SF  32.0    6-7   
315      Paul Millsap       Atlanta Hawks     4.0       PF  31.0    6-8   
..                ...                 ...     ...      ...   ...    ...   
374        JJ Hickson  Washington Wizards    21.0        C  27.0    6-9   
380    Garrett Temple  Washington Wizards    17.0       SG  30.0    6-6   
372       Drew Gooden  Washington Wizards    90.0       PF  34.0   6-10   
369      Bradley Beal  Washington Wizards     3.0       SG  22.0    6-5   
368     Alan Anderson  Washington Wizards     6.0       SG  33.0    6-6   

     Weight               College      Salary  
322   260.0                   NaN   1000000.0  
310   205.0              Michigan   1304520.0  
321   245.0                   NaN   9756250.0  
320   220.0                   NaN   4000000.0  
315   246.0        Louisiana Tech  18671659.0  
..      ...                   ...         ...  
374   242.0  North Carolina State    273038.0  
380   195.0                   LSU   1100602.0  
372   250.0                Kansas   3300000.0  
369   207.0               Florida   5694674.0  
368   220.0        Michigan State   4000000.0  

[457 rows x 9 columns]

In [23]:
nba.sort_index(axis=0, inplace = True)

### Rank Value Method


In [25]:
nba.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [27]:
nba['Salary'] = nba['Salary'].fillna(0).astype(int)

In [35]:
nba['Salary Rank'] = nba['Salary'].rank(ascending=False).astype(int)

In [39]:
nba.sort_values(by='Salary Rank', ascending = True)

Name                    Team  Number Position   Age Height  \
109      Kobe Bryant      Los Angeles Lakers    24.0       SF  37.0    6-6   
169     LeBron James     Cleveland Cavaliers    23.0       SF  31.0    6-8   
33   Carmelo Anthony         New York Knicks     7.0       SF  32.0    6-8   
251    Dwight Howard         Houston Rockets    12.0        C  30.0   6-11   
339       Chris Bosh              Miami Heat     1.0       PF  32.0   6-11   
..               ...                     ...     ...      ...   ...    ...   
409       Greg Smith  Minnesota Timberwolves     4.0       PF  25.0   6-10   
353    Dorell Wright              Miami Heat    11.0       SF  30.0    6-9   
46       Elton Brand      Philadelphia 76ers    42.0       PF  37.0    6-9   
270   Xavier Munford       Memphis Grizzlies    14.0       PG  24.0    6-3   
397     Axel Toupane          Denver Nuggets     6.0       SG  23.0    6-7   

     Weight       College    Salary  Salary Rank  
109   212.0           NaN  25000000            1  
169   250.0           NaN  22970500            2  
33    240.0      Syracuse  22875000            3  
251   265.0           NaN  22359364            4  
339   235.0  Georgia Tech  22192730            5  
..      ...           ...       ...          ...  
409   250.0  Fresno State         0          452  
353   205.0           NaN         0          452  
46    254.0          Duke         0          452  
270   180.0  Rhode Island         0          452  
397   210.0           NaN         0          452  

[457 rows x 10 columns]